<!DOCTYPE html>
<html>
<head>
    <title>Navi|Ninja World</title>
</head>
<body>
<h1><p align="center">Добро пожаловать в Navi|Ninja World!</p></h1>
    <p><h1>Мои Соцсети:</p></h1>
</body>
</html>
<p><h2>  Мой ютуб: <a href="https://youtube.com/@navi-ninja?si=Yz5UnY1AR3MnCSX7">YOUTUBE</a></p></h2>
</body>
</html>
<p><h2>  Мой Тик Ток: <a href="https://www.tiktok.com/@navininja52?_t=ZS-8tgGDEO4XNI&_r=1">TIK TOK</a></h3></p>
</body>
</html>
<style>
  body {
    background-image: url('https://images.wallpapersden.com/image/download/om-nom-cut-the-rope-art_ZmdqbmeUmZqaraWkpJRnZmtlrWhtaWU.jpg');
    background-repeat: no-repeat;
    background-size: cover;
  }
</style>
